<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>AI Toolkit Launcher</AssemblyName>
    <RootNamespace>AiToolkit.Launcher</RootNamespace>
    <AssemblyTitle>AI Toolkit Easy2Use Launcher</AssemblyTitle>
    <Product>AI Toolkit Easy2Use</Product>
    <Description>Windows portable environment manager and launcher</Description>
    <ApplicationIcon>..\..\ui\src\app\favicon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AI.Toolkit.Launcher.Core\AI.Toolkit.Launcher.Core.csproj" />
  </ItemGroup>
</Project>
